services:
  app:
    build: .
    container_name: chat_app
    restart: always
    expose:
      - 8000
    depends_on:
      - db
    volumes:
      - type: "bind"
        source: .
        target: /app
    env_file:
      - .env
  db:
      image: postgres:16
      container_name: chat_app_db
      restart: always
      expose:
        - 3306
      volumes:
        - chat_app_postgres:/var/lib/postgresql/data
      environment:
        POSTGRES_DB: chat_app
        POSTGRES_PASSWORD: test1234
  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080
volumes:
  chat_app_postgres: