services:
  app:
    build:
      context: .
      dockerfile: ./dockerfiles/chat_app/Dockerfile
    container_name: chat_app
    restart: always
    ports:
      - 8000:8000
    depends_on:
      - postgres
    volumes:
      - .:/app
    networks:
      - chat_app_network
    env_file:
      - .env
  postgres:
    build:
      dockerfile: ./dockerfiles/postgresql/Dockerfile
    container_name: chat_app_postgres
    restart: always
    ports:
      - 5433:5433
    volumes:
      - chat_app_postgres_volume:/var/lib/postgresql/pg_data
    networks:
      - chat_app_network
    environment:
      POSTGRES_DB: chat_app
      POSTGRES_PASSWORD: test1234
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - postgres
    networks:
      - chat_app_network

volumes:
  chat_app_postgres_volume:

networks:
  chat_app_network: