volumes:
  chat_app_postgres_volume:

networks:
  chat_app_network:

services:
  postgres:
    image: postgres:16
    container_name: chat_app_postgres
    restart: always
    expose:
      - 5432
    volumes:
      - chat_app_postgres_volume:/var/lib/postgresql/data
    networks:
      - chat_app_network
    environment:
      POSTGRES_DB: chat_app
      POSTGRES_PASSWORD: test1234
  app:
    build: .
    container_name: chat_app
    restart: always
    ports:
      - 8000:8000
    depends_on:
      - postgres
    volumes:
      - .:/app
    networks:
      - chat_app_network
    env_file:
      - .env
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - postgres
    networks:
      - chat_app_network

